language: generic
env:
  global:
    - I7_PREFIX: "/tmp/i7"
install: ./bootstrap.sh
script: ./build-code.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: ./FLexibleSurvival.materials/Release
  on:
    branch: master

notifications:
  email: false
sudo: false