language: generic
env:
  global:
    - I7_PREFIX: "/tmp/i721_inform"
install: ./bootstrap.sh
script: ./build-code.sh


notifications:
  email: false
sudo: false

before_deploy:
  - cd ./Release

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  skip_cleanup: true
  app: flexible-survival-deploy
  on:
    branch: master

cache:
    directories:
     - $I7_PREFIX  