language: generic
env:
  global:
    - I7_PREFIX: "/tmp/i7"
install: ./install-inform.sh $I7_PREFIX
script: $I7_PREFIX/bin/i7 -p $I7_PREFIX -r FlexibleSurvival.inform
after_success: ./push-folder-as-gh-pages.sh ./FLexibleSurvival.materials/Release

