language: generic
env:
  global:
    - I7_PREFIX: "/tmp/i7"
install: ./install-inform.sh $I7_PREFIX
script: $I7_PREFIX/bin/i7 -p $I7_PREFIX -r FlexibleSurvival.inform

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: ./FLexibleSurvival.materials/Release
  on:
    branch: master